apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vetu2irm3-go 
  janus-idp.io/tekton: vetu2irm3-go
  backstage.io/kubernetes-id: vetu2irm3-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vetu2irm3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml