apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vetu2irm3-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:7ce37f75de1742cdf7ee1384845eb17995da2929@sha256:e55d3d1def973a537bcbdaea5296dd881624ba7fcdcf1cf0f6148c318bd644c9
          name: container-image
